[package]
name = "nes"
version = "0.1.0"
authors = ["Henry Sloan <henryksloan@gmail.com>"]
edition = "2018"

[dependencies]
cpu = { path = "../cpu" }
ppu = { path = "../ppu" }
apu = { path = "../apu" }
memory = { path = "../memory" }